import { CometChatContext, CometChatContextProvider } from "./CometChatContext";

import {
  BaseStyle,
  BaseStyleInterface,
  BorderStyle,
  BorderStyleInterface,
  FontStyle,
  FontStyleInterface,
  ShadowStyle,
  ShadowStyleInterface,
  ImageType,
  CometChatContextType,
  CometChatTabAlignment,
  ConversationType,
  DatePattern,
  MessageReceipt
} from './base';

import { ChatConfigurator, DataSource, MessageDataSource, DataSourceDecorator, ExtensionsDataSource } from './framework';
import {
  CometChatOptions,
  CometChatMessageOption,
  CometChatMessageTemplate,
  CometChatDetailsTemplate,
  CometChatDetailsOption,
} from './modals';
import { CometChatLocalize, localize } from './resources/CometChatLocalize';
import { CometChatTheme, Palette, Typography } from './resources/CometChatTheme';
import { CometChatConversationEvents, CometChatGroupsEvents, CometChatUIEvents, MessageEvents, CometChatUIEventHandler } from "./events";
import {
  CometChatConversationUtils,
  getDefaultDetailsTemplate,
  CometChatLiveReactions,
  CometChatMessagePreview,
  MessagePreviewConfiguration,
  MessagePreviewStyle,
  CometChatSoundManager,
} from './utils';

import {
  CometChatListItem,
  CometChatListItemInterface,
  ListItemStyle,
  CometChatAvatar,
  CometChatBadge,
  CometChatStatusIndicator,
  CometChatReceipt,
  CometChatDate,
  AvatarConfiguration,
  BadgeConfiguration,
  BadgeStyle,
  DateConfiguration,
  ReceiptConfiguration,
  StatusIndicatorConfiguration,
  StatusIndicatorStyle,
  DateStyle,
  AvatarStyle,
  CometChatMessageInput,
  AudioBubbleStyle,
  AudioBubbleStyleInterface,
  CometChatAudioBubble,
  CometChatAudioBubbleInterface,
  CometChatFileBubble,
  CometChatFileBubbleInterface,
  FileBubbleStyle,
  FileBubbleStyleInterface,
  CometChatVideoBubble,
  CometChatVideoBubbleInterface,
  VideoBubbleStyle,
  VideoBubbleStyleInterface,
  CometChatTextBubble,
  CometChatTextBubbleInterface,
  TextBubbleStyle,
  TextBubbleStyleInterface,
  CometChatImageBubble,
  CometChatImageBubbleInterface,
  ImageBubbleStyle,
  ImageBubbleStyleInterface,
  //
  CometChatActionSheet,
  ActionSheetStyles,
  ActionItem,
  CometChatBottomSheet,
  CometChatConfirmDialog,
  ListItemStyleInterface,
  CometChatList,
  CometChatListProps,
  CometChatListActionsInterface,
  CometChatListStylesInterface,
  CometChatMediaRecorder,
  CometChatMediaRecorderInterface,
  MediaRecorderStyleInterface,
  MediaRecorderStyle,
  AvatarStyleInterface,
  ListItemConfiguration,
  CometChatConfirmDialogInterface,
  CometChatConfirmDialogStyleInterface,
  ActionItemInterface,
  ActionSheetStylesInterface,
  AvatarConfigurationInterface,
  BadgeConfigurationInterface,
  BadgeStyleInterface,
  CometChatBottomSheetInterface,
  CometChatDateInterface,
  CometChatMessageInputInterface,
  CometChatMessageInputStyleInterface,
  CometChatReceiptInterface,
  CometChatStatusIndicatorInterface,
  DateConfigurationInterface,
  DateStyleInterface,
  FormatTextForLinks,
  ReceiptConfigurationInterface,
  StatusIndicatorConfigurationInterface,
  StatusIndicatorStyleInterface,
} from './views';

import {
  CometChatUIKit,
  CometChatUIKitHelper,
  UIKitSettings,
} from "./CometChatUiKit";

import {
  CometChatMessageComposerActionInterface,
} from "./helper/types";

import * as CometChatUiKitConstants from './constants/UIKitConstants';

import { messageStatus } from './utils/CometChatMessageHelper/index'

export {
  CometChatContextProvider,
  CometChatUIEventHandler,
  CometChatUiKitConstants,
  messageStatus,
  CometChatConversationEvents,
  CometChatGroupsEvents,
  CometChatUIEvents,
  MessageEvents,
  CometChatTheme,
  Palette,
  Typography,
  ActionItemInterface,
  ActionSheetStylesInterface,
  AvatarConfigurationInterface,
  BadgeConfigurationInterface,
  BadgeStyleInterface,
  CometChatBottomSheetInterface,
  CometChatDateInterface,
  CometChatMessageInputInterface,
  CometChatMessageInputStyleInterface,
  CometChatReceiptInterface,
  CometChatStatusIndicatorInterface,
  DateConfigurationInterface,
  DateStyleInterface,
  FormatTextForLinks,
  ReceiptConfigurationInterface,
  StatusIndicatorConfigurationInterface,
  StatusIndicatorStyleInterface,
  DataSourceDecorator,
  ExtensionsDataSource,
  CometChatContextType,
  CometChatTabAlignment,
  ConversationType,
  DatePattern,
  MessageReceipt,
  CometChatUIKit,
  CometChatUIKitHelper,
  UIKitSettings,
  CometChatConfirmDialogInterface,
  CometChatConfirmDialogStyleInterface,
  CometChatContext,
  ListItemConfiguration,
  BaseStyle,
  BaseStyleInterface,
  BorderStyle,
  BorderStyleInterface,
  FontStyle,
  FontStyleInterface,
  ShadowStyle,
  ShadowStyleInterface,
  ImageType,
  CometChatMessageComposerActionInterface,
  //
  ChatConfigurator,
  DataSource,
  MessageDataSource,
  //
  CometChatOptions,
  CometChatMessageOption,
  CometChatMessageTemplate,
  CometChatDetailsTemplate,
  CometChatDetailsOption,
  //
  CometChatLocalize,
  localize,
  //
  CometChatConversationUtils,
  getDefaultDetailsTemplate,
  CometChatLiveReactions,
  //
  CometChatListItem,
  CometChatListItemInterface,
  ListItemStyleInterface,
  ListItemStyle,
  CometChatAvatar,
  CometChatBadge,
  CometChatStatusIndicator,
  CometChatReceipt,
  CometChatDate,
  AvatarConfiguration,
  BadgeConfiguration,
  BadgeStyle,
  DateConfiguration,
  ReceiptConfiguration,
  StatusIndicatorConfiguration,
  StatusIndicatorStyle,
  DateStyle,
  AvatarStyle,
  CometChatMessageInput,
  AudioBubbleStyle,
  AudioBubbleStyleInterface,
  CometChatAudioBubble,
  CometChatAudioBubbleInterface,
  CometChatFileBubble,
  CometChatFileBubbleInterface,
  FileBubbleStyle,
  FileBubbleStyleInterface,
  CometChatVideoBubble,
  CometChatVideoBubbleInterface,
  VideoBubbleStyle,
  VideoBubbleStyleInterface,
  CometChatTextBubble,
  CometChatTextBubbleInterface,
  TextBubbleStyle,
  TextBubbleStyleInterface,
  CometChatImageBubble,
  CometChatImageBubbleInterface,
  ImageBubbleStyle,
  ImageBubbleStyleInterface,
  AvatarStyleInterface,
  //
  CometChatActionSheet,
  ActionSheetStyles,
  ActionItem,
  CometChatBottomSheet,
  CometChatConfirmDialog,
  CometChatMessagePreview,
  MessagePreviewConfiguration,
  MessagePreviewStyle,
  CometChatSoundManager,
  //
  CometChatList,
  CometChatListProps,
  CometChatListActionsInterface,
  CometChatListStylesInterface,
  CometChatMediaRecorder,
  CometChatMediaRecorderInterface,
  MediaRecorderStyleInterface,
  MediaRecorderStyle,
};
