export const AppConstants = {
  fcmProviderId: '',
  apnsProviderId: '',
  authKey: '',
  appId: '',
  region: '',
  subscriptionType: 'ALL_USERS',
  versionNumber: 'V5.2.7',
  webClientId:
    '',
  iosClientId:
    '',
};

export const SCREEN_CONSTANTS = {
  LOGIN: 'Login',
  APP_CRED: 'AppCredentials',
  SAMPLE_USER: 'SampleUser',
  ONGOING_CALL_SCREEN: 'OngoingCallScreen',
  BOTTOM_TAB_NAVIGATOR: 'BottomTabNavigator',
  CHATS: 'Chats',
  CALLS: 'Calls',
  USERS: 'Users',
  GROUPS: 'Groups',
  CONVERSATION: 'Conversation',
  CREATE_CONVERSATION: 'CreateConversation',
  MESSAGES: 'Messages',
  SEARCH_MESSAGES: 'SearchMessages',
  THREAD_VIEW: 'ThreadView',
  USER_INFO: 'UserInfo',
  GROUP_INFO: 'GroupInfo',
  ADD_MEMBER: 'AddMember',
  TRANSFER_OWNERSHIP: 'TransferOwnershipSection',
  BANNED_MEMBER: 'BannedMember',
  VIEW_MEMBER: 'ViewMembers',
  CALL_LOGS: 'CallLogs',
  CALL_DETAILS: 'CallDetails',
  QR_SCREEN: 'QRScreen',
  AI_AGENTS: 'AIAgents',
} as const;
