# use_modular_headers!
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_frameworks! :linkage => :static

target 'SampleAppWithPushNotifications' do
  config = use_native_modules!

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'
  pod 'RNVoipPushNotification', :path => '../node_modules/react-native-voip-push-notification'

  

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'SampleAppWithPushNotifications'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = 'SampleAppWithPushNotifications-Bridging-Header.h'
        end
      end
    end

    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    # end
  end
end